### ISSUE TITLE
It doesn't work on ar3011（10.11.1）failed to reset

### ISSUE THREAD

**Issue by Skywol** [RehabMan/OS-X-Atheros-3k-Firmware#4]
When I put the kext in S/L/E,build cache and reboot. it report failed to reset the device

**Comment by Skywol** [comment]
My bluetooth PID 3002 VID 0CF3

**Comment by RehabMan** [comment]
You're not using the latest build.  I removed the check for error return from reset.  It works with 10.11 even though the reset call fails.
